[unstable]
registry-auth = true

[registry]
global-credential-providers = ["cargo:token"]

[registries.lithic]
index = "ssh://git@ssh.shipyard.rs/lithic/crate-index.git"
token = "${CARGO_REGISTRIES_LITHIC_TOKEN}"

[http]
user-agent = "shipyard ${CARGO_REGISTRIES_LITHIC_TOKEN}"

[net]
git-fetch-with-cli = true

[alias]
t = "test --workspace --lib"
ti = "test --workspace"     # includes integration tests
c = "clippy --workspace --all-targets"